name: "Build and Deploy"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout | Проверки
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Pages | Настройка страниц
        id: pages
        uses: actions/configure-pages@v1

      - name: Setup Ruby | Установка Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true

      - name: Build jekyll/builder | Подготовка Jekyll/builder
        run: bundle install

      - name: Build site | Создание сайта
        run: bundle exec jekyll b -d "_site"
        env:
          JEKYLL_ENV: "production"

      - name: List files in _site | Проверка содержимого
        run: ls -R _site

      - name: Upload site artifact | Загрузка осколков
        uses: actions/upload-artifact@v4
        with:
          name: site-artifact
          path: "_site"
          retention-days: 1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download site artifact | Загрузка артефакта
        uses: actions/download-artifact@v4
        with:
          name: site-artifact
          path: _site

      - name: List downloaded files | Проверка загруженных файлов
        run: ls -R _site

      - name: Deploy to GitHub Pages | Загрузка на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
